# Generated by Django 4.2.1 on 2023-08-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Shoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(blank=True, upload_to='products/')),
                ('url', models.CharField(max_length=350)),
                ('price', models.PositiveIntegerField()),
            ],
        ),
    ]
