# Generated by Django 4.2.1 on 2023-08-12 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_shoes_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shoes',
            name='img',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
